### PR TITLE
Native tool support for llama3.1 and mistral large models and add chat support for llama3.1, llama3 and mistral large

### PR DESCRIPTION
**Pull request by bamless**
Refactored prompt generation in `ChatWatsonx` to use a more flexible jinja2 template based approach. This should make adding support for new chat-enabled models in watsonx.ai more easy.
With this change, support for llama3, llama3.1 and mistral large models has been added in `ChatWatsonx`.  Support for 'ibm/granite-13b-chat-v1' has been removed since (as far as I can tell) it isn't present anymore in watsonx.ai.

This PR also adds native tool support for models that support them (for now, the llama3.1 family and mistral large). Previously, tool support was enabled only for 'mixtral-8x7b-instruct-v01', which doesn't support native function calling (via special tokens), making results flaky at best. The new models behave much better in complex function calling situations, as they've been trained on such use-cases and provide bespoke tokens to signal when the model wants to make a function call and for passing the result back to the model.
New integration tests have been added to check that the implementation actually matches model's spec. by checking the results of a simple tool calling prompt scenario.

Also, new unit tests have been added to check that chat models templates actually adhere to the specific model prompt format.

Resources used for setting up chat prompt templates and function callling templates:
 - [Llama3.1 json function calling and prompt format](https://llama.meta.com/docs/model-cards-and-prompt-formats/llama3_1/#json-based-tool-calling)
 - [Mistral function calliong and prompt format](https://github.com/mistralai/mistral-common/blob/main/examples/tokenizer.ipynb) & [Mistral tool_call_id generation](https://github.com/mistralai/mistral-common/blob/00780973136e3dac4d541e0712174eb34016debf/src/mistral_common/protocol/instruct/validator.py#L307)
  - [Granite prompt format](https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/fm-models-ibm-chat.html?context=wx)
  
 Future work:
 Given that this PR allows tool support (`bind_tools` and friends) only for model with native support for them, and that all currently supported tool calling LLMs generate a special token at the _start_ of a generation, streaming support for a tool-calling `ChatWatsonx` should be feasible with a small amount of buffering. Waiting for the first non-empy token and checking if it is the model's tool-call signaling token should be enough to differentiate between a normal response and a tool call response. If it's the first, all model output should be parsed before returning an `AIMessage` with tool calls to the user. If it's the second we can start streaming `AIMessageChunks` to the user right after the tool-call token check.  
If this PR gets merged, I can start looking at an implementation for this.

### CODE REVIEW

**Comment by bamless** [comment]
Any feedback would be appreciated, especially on double-checking the prompt formats (correct white-space, correct positioning of model tags) as the models could be really sensitive to a slightly wrong prompts (especially on long chats)

**Comment by bamless** [comment]
Doing some more research, I stumbled on the `chat_template` field of `tokenizer_config.json` in the mistral and llama3.1 hugging face repositories (https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct/blob/main/tokenizer_config.json#L2053 and https://huggingface.co/mistralai/Mistral-Large-Instruct-2407/blob/main/tokenizer_config.json#L6176)

I believe they are used in the [transformer chat template API](https://huggingface.co/docs/transformers/main/en/chat_templating). They also use jinja2 as a templating engine, and they seem comparable to the templates provided in this PR, though they support more complex configuration (for example the llama3.1 one can switch between different tool calling modes, as explained in the model card) and they do more exaustive sanity checks on messages (only one system message etc...).

Could it be worthwhile making a more direct port of these templates to ensure correct prompt rendering? Maybe only adding unit tests against these templates could be more simple, while not complicating the code too much.

**Comment by LukaszCmielowski** [comment]
@bamless is there any reason why this PR has been closed ?. 
fyi: the wx dev team is working on supporting those models via CHAT REST API backend code.

**Comment by bamless** [comment]
Sorry, should've gotten back on this but it slipped my mind. With a couple of colleagues we're working on porting the actual prompt templates from HF to a fork of this PR as well as implementing a couple of QOL improvement to the API. We're also working on adding support for some other IBM services in the form of retrievers and chat histories. Once we have a good enough working environment we plan to open other PRs.

**Pull request closed without merging**
